### ISSUE TITLE
Render the environment

### ISSUE THREAD

**Issue by dkal3** [nickjalbert/la_deep_rl_meet_1#2]
Hi!!!
Firstly i would like to congratulate you on the great job you have done! I've been searching a lot about creating my own environment in OpenAI and yours is the best I've found!
I would like to ask if we want to see the environment in the screen we have to implement render function, right? Do you know how this would be done?
Thank you in advance!!!

**Comment by nickjalbert** [comment]
Howdy!

The `render()` method is non-essential in the sense that you can still use most off-the-shelf RL libraries without implementing a `render()` for your environment.  However, it can still be useful to implement a `render()` for debugging and visualization purposes.  The specifics of how you'd go about implementing `render()` depends on your development environment.  A few thoughts:

* Do you need a render?  Perhaps you can get away with taking the state returned by your `step()` call and do something simple like printing it out to the terminal or plugging the state into your favorite visualization library.  This is the tactic I used when [I made a browser-based CartPole port](https://convexopt.com/cartpole/).
* It might be worth taking a look at some of the implementations in OpenAI's gym.  Check out [the implementation for CartPole's render](https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L137); essentially they construct an image based on the state and return that.
* I've had some luck rendering in Google Collab's online environment using [the techniques described in this StackOverflow question](https://stackoverflow.com/questions/50107530/how-to-render-openai-gym-in-google-colab). 

I think the high-level takeaway is that there's a lot of approaches to rendering your environment and the best approach depends on exactly what you're trying to accomplish.  Hope that helps a bit!

**Comment by dkal3** [comment]
OK!!!
Very useful info!! I think I will try the first one!
Thank you for your time!!!
